### ISSUE TITLE
Few questions about the paper

### ISSUE THREAD

**Issue by 903124** [kathrinse/be_great#3]
(Since there is no discussion page in this repo I'd leave it here on issue page)

1. Currently only one conditional_col is allowed during fit/sample is it theoretically possible to have multiple columns for it?
2. It's a bit slow to train the data is it possible to rewrite in efficient transformer in future work>
3. In `great_sample` only single sample of data is returned for each prompt is it able to return multiple at a same time?

Thanks for the work!

**Comment by unnir** [comment]
Hi, 

Thank you for your questions! 

> Currently only one conditional_col is allowed during fit/sample is it theoretically possible to have multiple columns for it?
Yes! That's the beauty of our approach, we are currently working on the `great_sample` function, which will have this functionality. 
Nevertheless, if you want to use GReaT for the multi-conditional sampling, I can provide you my custom sampling function, that I have used. 

>It's a bit slow to train the data is it possible to rewrite in efficient transformer in future work
We suggest using a machine with GPUs, since GReaT is based on large transformer networks. 
Also, we will try to introduce some tricks for fine-tuning in the future to speed up, but I would not expect a dramatic increase here to be honest. Another thing, we are going to share pretraining models for future use, for example we have fine-tuned models for Adult, California housing, and so datasets. 

> In `great_sample` only single sample of data is returned for each prompt is it able to return multiple at a same time?
I believe not, but we'll definitely add this in the next release. 
Or I might be wrong here, @kathrinse
Also, I believe with my custom sampling function; it can be achived. 

> (Since there is no discussion page in this repo I'd leave it here on issue page)
Did not GitHub has a discussion page, we might add it in the future, thanks!
